services:
  - type: web
    name: csgosaller
    env: python
    pythonVersion: "3.11"
    buildCommand: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      source $HOME/.cargo/env
      pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11